### ISSUE TITLE
Trade offers or live trading?

### ISSUE THREAD

**Issue by droblue** [Zwork101/steam-trade#3]
Basically is this just to accept trade offers or does this support live trading as i am in need of a live steam trading module

**Comment by ZeusJunior** [comment]
It works through trade offers

**Comment by Zwork101** [comment]
Currently, there is no way to send offers. However, that is a feature to be added in the future! If you look in the ETradeOffer file, you'll see that I've already started. For live trade offers,l I'd have to do more research, and it might take awhile.

**Comment by droblue** [comment]
I’ll do my own research into it it would be great to have a python module capable of live trading
